#!/usr/bin/env python
"""An alternate to nosetests that uses the plugin without installation."""
import os
import sys
import nose

here = os.path.dirname(__file__)
try:
    import alfajor
except ImportError:
    sys.path.append(os.path.join(here, os.path.pardir))

from alfajor.runners.nose import Alfajor


path = os.environ.get('PATH', '')
os.environ['PATH'] = path + os.pathsep + here
nose.main(addplugins=[Alfajor()])
